#!/usr/bin/env bash
# Déploie le shim httpdocs et les assets publics Ouvaton.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# shellcheck source=lib/lftp-escape.sh
source "${SCRIPT_DIR}/lib/lftp-escape.sh"

OUVATON_DEPLOY_PORT="${OUVATON_DEPLOY_PORT:-115}"
PUBLIC_DIR="${PUBLIC_DIR:-${PROJECT_ROOT}/deploy-staging/public}"
DRY_RUN="${KERMESSE_DEPLOY_HTTPDOCS_DRY_RUN:-false}"

fail() {
  printf '::error::%s\n' "$1" >&2
  exit 1
}

require_env() {
  local name="$1"
  if [ -z "${!name:-}" ]; then
    fail "${name} is required."
  fi
}

validate_remote_path() {
  local name="$1" value="$2"

  if [ -z "${value}" ]; then
    fail "${name} is required."
  fi

  if [[ "${value}" = /* || "${value}" = *..* ]]; then
    fail "${name} must be a relative folder path without '..'."
  fi

  if [[ ! "${value}" =~ ^[A-Za-z0-9_-]+(/[A-Za-z0-9_-]+)*$ ]]; then
    fail "${name} contains invalid characters."
  fi
}

lftp_q() {
  printf "'%s'" "$(lftp_squote "$1")"
}

require_env OUVATON_DEPLOY_HOST
require_env OUVATON_DEPLOY_USERNAME
require_env OUVATON_DEPLOY_PASSWORD
validate_remote_path OUVATON_DEPLOY_REMOTE_FOLDER "${OUVATON_DEPLOY_REMOTE_FOLDER:-}"
validate_remote_path OUVATON_HTTPDOCS_FOLDER "${OUVATON_HTTPDOCS_FOLDER:-}"

if [[ ! "${OUVATON_DEPLOY_HOST}" =~ ^[A-Za-z0-9._-]+$ ]]; then
  fail "OUVATON_DEPLOY_HOST contains invalid characters."
fi

if [[ ! "${OUVATON_DEPLOY_PORT}" =~ ^[0-9]+$ ]]; then
  fail "OUVATON_DEPLOY_PORT must be numeric."
fi

if [ ! -d "${PUBLIC_DIR}" ]; then
  fail "Public directory not found: ${PUBLIC_DIR}"
fi

if [ ! -f "${PUBLIC_DIR}/.htaccess" ]; then
  fail "Missing ${PUBLIC_DIR}/.htaccess."
fi

if [ ! -d "${PUBLIC_DIR}/assets" ]; then
  fail "Missing ${PUBLIC_DIR}/assets directory."
fi

SHIM_FILE="${HTTPDOCS_SHIM_FILE:-$(mktemp "${TMPDIR:-/tmp}/kermesse-httpdocs-index.XXXXXX.php")}"

{
  printf '<?php\n'
  printf '\n'
  printf 'use CodeIgniter\\Boot;\n'
  printf 'use Config\\Paths;\n'
  printf '\n'
  printf '// Ouvaton entry point - generated by scripts/deploy-httpdocs.sh.\n'
  printf '// httpdocs/ is the fixed web root; the CodeIgniter application lives\n'
  printf '// in the sibling %s/ directory.\n' "${OUVATON_DEPLOY_REMOTE_FOLDER}"
  printf "define('FCPATH', __DIR__ . DIRECTORY_SEPARATOR);\n"
  printf 'if (getcwd() . DIRECTORY_SEPARATOR !== FCPATH) { chdir(FCPATH); }\n'
  printf "\$deployRoot = realpath(__DIR__ . '/../%s');\n" "${OUVATON_DEPLOY_REMOTE_FOLDER}"
  printf "if (\$deployRoot === false) { http_response_code(500); exit('Deploy root is not available.'); }\n"
  printf "\$appRoot = realpath(\$deployRoot . '/current');\n"
  printf "if (\$appRoot === false) {\n"
  printf "    \$pointerContent = @file_get_contents(\$deployRoot . '/CURRENT_RELEASE');\n"
  printf "    if (\$pointerContent !== false) {\n"
  printf "        \$releaseName = basename(trim((string) \$pointerContent));\n"
  printf "        if (\$releaseName !== '') {\n"
  printf "            \$appRoot = realpath(\$deployRoot . '/releases/' . \$releaseName);\n"
  printf "        }\n"
  printf "    }\n"
  printf "}\n"
  printf "if (\$appRoot === false) { http_response_code(503); exit('No active release is available.'); }\n"
  printf "require \$appRoot . '/app/Config/Paths.php';\n"
  printf '$paths = new Paths();\n'
  printf "\$paths->envDirectory = realpath(\$deployRoot . '/shared');\n"
  printf "if (\$paths->envDirectory === false) { http_response_code(500); exit('Shared directory is not available.'); }\n"
  printf "\$paths->writableDirectory = realpath(\$deployRoot . '/shared/writable');\n"
  printf "if (\$paths->writableDirectory === false) { http_response_code(500); exit('Shared writable directory is not available.'); }\n"
  printf "require \$paths->systemDirectory . '/Boot.php';\n"
  printf 'exit(Boot::bootWeb($paths));\n'
} > "${SHIM_FILE}"

{
  printf 'set cmd:fail-exit yes\n'
  printf 'set net:max-retries 3\n'
  printf 'set net:timeout 60\n'
  printf "open -u %s,%s -p %s sftp://%s\n" \
    "$(lftp_q "${OUVATON_DEPLOY_USERNAME}")" \
    "$(lftp_q "${OUVATON_DEPLOY_PASSWORD}")" \
    "${OUVATON_DEPLOY_PORT}" \
    "${OUVATON_DEPLOY_HOST}"

  for writable_dir in cache logs session uploads; do
    remote_writable="${OUVATON_DEPLOY_REMOTE_FOLDER}/shared/writable/${writable_dir}"
    printf 'mkdir -p -f %s\n' "$(lftp_q "${remote_writable}")"
    printf 'cd %s\n' "$(lftp_q "${remote_writable}")"
    printf 'cd /\n'
  done

  printf 'cd %s\n' "$(lftp_q "${OUVATON_HTTPDOCS_FOLDER}")"
  printf 'put %s -o index.php\n' "$(lftp_q "${SHIM_FILE}")"
  printf 'put %s -o .htaccess\n' "$(lftp_q "${PUBLIC_DIR}/.htaccess")"
  if [ -f "${PUBLIC_DIR}/ops-bootstrap-activate.php" ]; then
    printf 'put %s -o ops-bootstrap-activate.php\n' "$(lftp_q "${PUBLIC_DIR}/ops-bootstrap-activate.php")"
  fi
  if [ -f "${PUBLIC_DIR}/robots.txt" ]; then
    printf 'put %s -o robots.txt\n' "$(lftp_q "${PUBLIC_DIR}/robots.txt")"
  fi
  printf 'lcd %s\n' "$(lftp_q "${PUBLIC_DIR}")"
  printf 'mirror --reverse --delete assets/ assets/\n'
  printf 'bye\n'
} > "${SHIM_FILE}.lftp"

if [ "${DRY_RUN}" = "true" ]; then
  cat "${SHIM_FILE}.lftp"
  exit 0
fi

lftp -f "${SHIM_FILE}.lftp"
