#!/bin/bash
# Removes ChrootDirectory from the sshd_config generated by atmoz/sftp's create-sftp-user.
# Runs after user creation but before sshd starts (via /etc/sftp.d/ hook).
#
# Why: ChrootDirectory requires root:root ownership on the chroot dir (/home/deploy).
# deploy-web's entrypoint chowns /srv/deploy-data (= /home/deploy) to www-data so that
# PHP can write CURRENT_RELEASE and the current symlink there. These two requirements
# are incompatible in a shared volume. This is a local rehearsal container — the chroot
# security is not needed here.
set -euo pipefail

sed -i '/^\s*ChrootDirectory/d' /etc/ssh/sshd_config

# Fix ownership back to www-data (UID 33) so deploy-web can write symlinks and files
chown 33:33 /home/deploy
